version: '3.10'

services:
  chatbot:
    container_name: chatbot
    build: .
    expose:
      - 3300
    environment:
      # - CHATID_PHONE=
      - CHATID_PHONE=
      - URL=
      - CONTENT_TYPE=application/json

  proxymanager:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt